idx_to_class = {
    0: "Abra",
    1: "Alakazam",
    2: "Arcanine",
    3: "Beedrill",
    4: "Bill",
    5: "Blastoise",
    6: "Bulbasaur",
    7: "Caterpie",
    8: "Chansey",
    9: "Charizard",
    10: "Charmander",
    11: "Charmeleon",
    12: "Clefairy Doll",
    13: "Clefairy",
    14: "Computer Search",
    15: "Defender",
    16: "Devolution Spray",
    17: "Dewgong",
    18: "Diglett",
    19: "Doduo",
    20: "Double Colorless Energy",
    21: "Dragonair",
    22: "Dratini",
    23: "Drowzee",
    24: "Dugtrio",
    25: "Electabuzz",
    26: "Electrode",
    27: "Energy Removal",
    28: "Energy Retrieval",
    29: "Farfetch'd",
    30: "Fighting Energy",
    31: "Fire Energy",
    32: "Full Heal",
    33: "Gastly",
    34: "Grass Energy",
    35: "Growlithe",
    36: "Gust of Wind",
    37: "Gyarados",
    38: "Haunter",
    39: "Hitmonchan",
    40: "Impostor Professor Oak",
    41: "Item Finder",
    42: "Ivysaur",
    43: "Jynx",
    44: "Kadabra",
    45: "Kakuna",
    46: "Koffing",
    47: "Lass",
    48: "Lightning Energy",
    49: "Machamp",
    50: "Machoke",
    51: "Machop",
    52: "Magikarp",
    53: "Magmar",
    54: "Magnemite",
    55: "Magneton",
    56: "Maintenance",
    57: "Metapod",
    58: "Mewtwo",
    59: "Nidoking",
    60: "Nidoran♂",
    61: "Nidorino",
    62: "Ninetales",
    63: "Onix",
    64: "Pidgeotto",
    65: "Pidgey",
    66: "Pikachu",
    67: "PlusPower",
    68: "Pokédex",
    69: "Pokémon Breeder",
    70: "Pokémon Center",
    71: "Pokémon Flute",
    72: "Pokémon Trader",
    73: "Poliwag",
    74: "Poliwhirl",
    75: "Poliwrath",
    76: "Ponyta",
    77: "Porygon",
    78: "Potion",
    79: "Professor Oak",
    80: "Psychic Energy",
    81: "Raichu",
    82: "Raticate",
    83: "Rattata",
    84: "Revive",
    85: "Sandshrew",
    86: "Scoop Up",
    87: "Seel",
    88: "Squirtle",
    89: "Starmie",
    90: "Staryu",
    91: "Super Energy Removal",
    92: "Super Potion",
    93: "Switch",
    94: "Tangela",
    95: "Venusaur",
    96: "Voltorb",
    97: "Vulpix",
    98: "Wartortle",
    99: "Water Energy",
    100: "Weedle",
    101: "Zapdos"
}
